quarkus.roq.site-dir=src/main/resources
quarkus.roq.site.url=https://kcli.ch

# Development settings
%dev.quarkus.http.port=8080
%dev.quarkus.live-reload.watched-resources=templates,content,static

roq-default.uuid=${quarkus.uuid}
